### PR TITLE
Date fun 0.0.1

### PR DESCRIPTION
**Pull request by tanhaican**
增加日期相关处理函数（依赖 moment.js）
新增函数如下：
now
dateAdd
dateSubtract
datesDiff
dateGet

### CODE REVIEW

**Comment by silentmatt** [comment]
Thanks for the pull request! I like the idea of this, but I'd like to avoid run-time dependencies to keep the library small. Of course, you're welcome to use your own fork with these, or you might want to consider adding them as user-defined functions. You can do that by creating a `Parser` instance, then adding the custom functions to the `yourParserInstance.functions` object.

I'll create an issue for adding date and time functions, but using built-in JavaScript methods, and try to get them into the next major release.

**Comment by tanhaican** [comment]
Welcome back, and Thank you so much!
It would be great that if you can write sth about how to add custom function into README. One of the reasons I pull request was that I didn't know how to add one.

**Comment by silentmatt** [comment]
@tanhaican Good point, I just added some examples to the README. See https://github.com/silentmatt/expr-eval#custom-functions

**Comment by rubenstolk** [comment]
@tanhaican I've found this very helpful in combination with https://date-fns.org:

```js
for (key in dateFns) {
  parser.functions[key] = dateFns[key].bind(dateFns);
}
```

**Pull request closed without merging**
