### PR TITLE
Updated Typescript typings

### PR DESCRIPTION
**Pull request by Gillardo**
functions is missing from Parser typings.
Changed evaluate to return `any` instead of `number` as can be used to return `Date` or `text` if needed
package-lock.json file should be added to source control

### CODE REVIEW

**Comment by silentmatt** [comment]
Thanks for submitting this, and help is always welcome :) I'll leave the issue open for now until I can make sure there aren't other issues with the type definitions, but I'll get this merged and released first.

**Comment by silentmatt** [comment]
@Gillardo Just thought I'd ping you to let you know that this is published to npm (version 2.1.2).

**Comment by Gillardo** [comment]
Star!

**Comment by Gillardo** [comment]
@silentmatt never thought about writing this library in typescript so you can generate the typings automatically, let alone get all the benefits of typescript over javascript..?

**Comment by Gillardo** [comment]
Nah fair point. I may start it on my branch if your interested. Don't think it would take me very long....

**Comment by silentmatt** [comment]
Go for it (if you want to of course).

**Pull request merged**
